name: Build Switch NRO

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    # On utilise l'image officielle de devkitPro pour Switch
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          # On s'assure que les outils sont bien dans le PATH
          export PATH=$DEVKITPRO/devkitA64/bin:$PATH
          make
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MonLauncher-NRO
          path: ./*.nro
